--!strict
return {
	Tusk = {
		Barrage = {
			Damage = 1.2,
			Duration = 5,
			StunTime = 0.3,
		},
		M1 = {
			[1] = {
				Damage = 5,
				StunTime = 0.8,
				Endlag = 0.15,
			},
			[2] = {
				Damage = 5,
				StunTime = 0.8,
				Endlag = 0.15,
			},
			[3] = {
				Damage = 5,
				StunTime = 0.8,
				Endlag = 0.15,
			},
			[4] = {
				Damage = 5,
				StunTime = 0.8,
				Endlag = 0.15,
			},
			[5] = {
				Damage = 5,
				StunTime = 0.8,
				Endlag = 0.15,
			},
		}
	}
}